spring:
  application:
    name: authority-basis

  jpa:
    generate-ddl: true
    showSql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL5Dialect

  datasource:
      url: jdbc:mysql://localhost:3306/auth?useSSL=false&useUnicode=true&characterEncoding=UTF-8
      username: chenyong
      password: a123456
      driver-class-name: com.mysql.jdbc.Driver
      tomcat:
        min-idle: 2
        test-while-idle: true
        test-on-borrow: true
        validation-query: SELECT 1
        time-between-eviction-runs-millis: 30000

server:
  port: 8181
